name: CI / publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    name: Build site (Hugo)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.152.2'
          extended: true

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '22'

      - name: Build site
        run: hugo -e production --gc --minify --cleanDestinationDir --baseURL="/"

      - name: Build search index
        run: npx -y pagefind --site public

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: ./public

      - name: Upload public directory
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build
          path: ./public
          retention-days: 1

  s3_sync:
    name: S3 sync to garage
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download public artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: build
          path: build

      - name: Set-up s5cmd
        uses: peak/action-setup-s5cmd@main
        with:
          version: v2.3.0

      - name: Sync to S3
        run: s5cmd --endpoint-url $AWS_ENDPOINT sync --delete build/ s3://homepage/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.GARAGE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.GARAGE_SECRET_KEY }}
          AWS_ENDPOINT: ${{ secrets.GARAGE_ENDPOINT }}
          AWS_DEFAULT_REGION: ${{ secrets.GARAGE_DEFAULT_REGION }}

      - name: Purge Cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@eee6dba0236093358f25bb1581bd615dc8b3d8e3 # v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_IDENTIFIER }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

  github_pages:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
